const Map<String, String> domainStatus = {
  'addPeriod': '新注册期',
  'autoRenewPeriod': '自动续费期',
  'clientDeleteProhibited': '注册商设置禁止删除',
  'clientHold': '注册商设置暂停解析',
  'clientLock': '注册商设置锁定',
  'clientRenewProhibited': '注册商设置禁止续费',
  'clientTransferProhibited': '注册商设置禁止转移',
  'clientUpdateProhibited': '注册商设置禁止更新',
  'inactive': '未激活',
  'ok': '正常',
  'pendingCreate': '待创建',
  'pendingDelete': '待删除',
  'pendingRenew': '待续费',
  'pendingRestore': '待恢复',
  'pendingTransfer': '待转移',
  'pendingUpdate': '待更新',
  'pendingVerification': '待验证',
  'redemptionPeriod': '赎回期',
  'renewPeriod': '续费期',
  'serverDeleteProhibited': '注册局设置禁止删除',
  'serverHold': '注册局设置暂停解析',
  'serverLock': '注册局设置锁定',
  'serverRenewProhibited': '注册局设置禁止续费',
  'serverTransferProhibited': '注册局设置禁止转移',
  'serverUpdateProhibited': '注册局设置禁止更新',
  'transferPeriod': '转移期',
};
